In [1]:
#read the information of A1-synthetic.txt and load it into a dataframe to preprocess it
import pandas as pd
import numpy as np


#read the .txt file 
df = pd.read_table('Data/A1-synthetic.txt', delimiter = '\t')
df.head()

,#v1,v2,v3,v4,v5,v6,v7,v8,v9,z
0,37.344110,10.542156,0.969185,3.568534,96.798733,3.429026,75.810196,0,20.002459,11.805369
1,4.089849,11.894301,0.467775,1.279044,100.149383,3.190073,76.423095,0,12.702628,5.125025
2,-32.333439,10.968631,0.238486,1.410745,100.642075,3.093934,78.758727,1,10.723848,3.218553
3,-45.632977,11.509606,0.924938,3.404069,105.963016,2.884269,83.027750,0,19.946593,12.955092
4,-41.543394,10.117186,0.315180,1.020120,97.371423,2.815820,77.194463,0,11.105024,1.919094

In [2]:
#print the number of rows and columns
print(df.shape)
print(df.columns)
print(df.columns[0])
print(df[df.columns[0]])
print(min(df[df.columns[0]]))

(1000, 10)
Index(['#v1', 'v2', 'v3', 'v4', 'v5', 'v6', 'v7', 'v8', 'v9', 'z'], dtype='object')
#v1
0      37.344110
1       4.089849
2     -32.333439
3     -45.632977
4     -41.543394
         ...
995     3.792427
996   -15.036910
997     3.448645
998    44.874246
999    19.611066
Name: #v1, Length: 1000, dtype: float64
-49.94291004

In [3]:
#preprocess input 9 columns to scale it's values from 0 to 1
columns = df.shape[1]
inputcolumns = df.columns[0 : 9]
smin = 0
smax = 1
df_normalized = df
for inp_col in inputcolumns:
    column_values = df[inp_col]
    #print(column_values)
    xmin = min(column_values)
    xmax = max(column_values)
    #print( smin + ((smax - smin) / (xmax - xmin) ) * (df[inp_col] - xmin) )
    df_normalized[inp_col] = np.round(smin + ((smax - smin) / (xmax - xmin) ) * (df[inp_col] - xmin), 4)
print(df_normalized)

        #v1      v2      v3      v4      v5      v6      v7   v8      v9  \
0    0.8743  0.2712  0.9694  0.8561  0.3747  0.8943  0.4149  0.0  0.8298
1    0.5412  0.9475  0.4678  0.0923  0.4825  0.7475  0.4341  0.0  0.2181
2    0.1764  0.4845  0.2384  0.1362  0.4984  0.6884  0.5072  1.0  0.0523
3    0.0432  0.7551  0.9252  0.8013  0.6695  0.5595  0.6408  0.0  0.8251
4    0.0841  0.0586  0.3152  0.0059  0.3932  0.5174  0.4583  0.0  0.0842
..      ...     ...     ...     ...     ...     ...     ...  ...     ...
995  0.5383  0.2837  0.9130  0.9699  0.4359  0.7671  0.4725  0.0  0.7377
996  0.3496  0.8199  0.9888  0.7341  0.7229  0.7760  0.6827  0.0  0.9530
997  0.5348  0.4097  0.7992  0.9213  0.5035  0.2167  0.5226  0.0  0.5787
998  0.9498  0.1361  0.0611  0.0886  0.4755  0.6181  0.5290  0.0  0.0032
999  0.6967  0.9955  0.2007  0.0587  0.4675  0.3975  0.4132  0.0  0.0405

             z
0    11.805369
1     5.125025
2     3.218553
3    12.955092
4     1.919094
..         ...
995  11.265913
996  15.061569
997  11.029825
998   1.580719
999   3.665128

[1000 rows x 10 columns]

In [4]:
#preprocess output 10th column to scale it's values from 0.1 to 0.9
columns = df.shape[1]
outputcolumn = df.columns[9]
smin = 0.1
smax = 0.9

column_values = df[outputcolumn]
xmin = min(column_values)
xmax = max(column_values)
df_normalized[outputcolumn] = np.round(smin + ((smax - smin) / (xmax - xmin) ) * (df[outputcolumn] - xmin), 4)
print(df_normalized)

        #v1      v2      v3      v4      v5      v6      v7   v8      v9  \
0    0.8743  0.2712  0.9694  0.8561  0.3747  0.8943  0.4149  0.0  0.8298
1    0.5412  0.9475  0.4678  0.0923  0.4825  0.7475  0.4341  0.0  0.2181
2    0.1764  0.4845  0.2384  0.1362  0.4984  0.6884  0.5072  1.0  0.0523
3    0.0432  0.7551  0.9252  0.8013  0.6695  0.5595  0.6408  0.0  0.8251
4    0.0841  0.0586  0.3152  0.0059  0.3932  0.5174  0.4583  0.0  0.0842
..      ...     ...     ...     ...     ...     ...     ...  ...     ...
995  0.5383  0.2837  0.9130  0.9699  0.4359  0.7671  0.4725  0.0  0.7377
996  0.3496  0.8199  0.9888  0.7341  0.7229  0.7760  0.6827  0.0  0.9530
997  0.5348  0.4097  0.7992  0.9213  0.5035  0.2167  0.5226  0.0  0.5787
998  0.9498  0.1361  0.0611  0.0886  0.4755  0.6181  0.5290  0.0  0.0032
999  0.6967  0.9955  0.2007  0.0587  0.4675  0.3975  0.4132  0.0  0.0405

          z
0    0.6973
1    0.3805
2    0.2901
3    0.7518
4    0.2285
..      ...
995  0.6717
996  0.8517
997  0.6605
998  0.2125
999  0.3113

[1000 rows x 10 columns]

In [5]:
# Write normalized DataFrame to a table-like format (CSV file)
df_normalized.to_csv('Normalized Data/A1-synthetic_normalized.txt', index=False, sep='\t')